
title: Jekyll Talks Theme Sample


collections:
  talks:
    output: true

defaults:
- scope:
    path: ""
    type: talks
  values:
    layout: blank


#########################
# more settings

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: css
  style: expanded

exclude:
- README.md
